server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tonsaito/configuration-repo.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/